DROP TABLE app_user_notification_rule_param CASCADE;
DROP TABLE app_user_notification_rule_channel CASCADE;
DROP TABLE app_user_notification_rule_validator CASCADE;
DROP TABLE app_user_notification_rule CASCADE;
DROP TYPE IF EXISTS app_notification_period_type;