[common]
recovery_retry_seconds = 5

[substrate]
chain = "kusama"
chain_display = "Kusama"
# Kusama    0xB0A8D493285C2DF73290DFB7E61F870F17B41801197A149CA93654499EA3DAFE
# Polkadot  0x91B171BB158E2D3848FA23A9F1C25182FB8E20313B2C1EB49219DA7A70CE90C3
chain_genesis_hash = "0xB0A8D493285C2DF73290DFB7E61F870F17B41801197A149CA93654499EA3DAFE"
# number of epochs per era
epochs_per_era = 6
rpc_url = "wss://rpc.helikon.io/kusama"
people_rpc_url = "wss://rpc.helikon.io/people-kusama"
connection_timeout_seconds = 30
request_timeout_seconds = 30
# for internal use, 1 for Kusama, 2 for Polkadot
network_id = 1
token_ticker = "KSM"
token_decimals = 12
token_format_decimal_points = 4

[log]
subvt_level = "debug"
other_level = "warn"

[rpc]
host = "0.0.0.0"
network_status_port = 7888
active_validator_list_port = 7889
inactive_validator_list_port = 7890
validator_details_port = 7891

[http]
request_timeout_seconds = 60
service_host = "0.0.0.0"
report_service_port = 7900
app_service_port = 7901

[redis]
url = "redis://127.0.0.1:6379/"
kusama_url = "redis://127.0.0.1:6379/"
polkadot_url = "redis://127.0.0.1:6379/"
westend_url = "redis://127.0.0.1:6379/"

[app_postgres]
host = "127.0.0.1"
port = 5432
username = "subvt"
password = "subvt"
database_name = "subvt_app"
pool_max_connections = 7
connection_timeout_seconds = 3

[network_postgres]
host = "127.0.0.1"
port = 5432
username = "subvt"
password = "subvt"
database_name = "subvt_network"
pool_max_connections = 7
connection_timeout_seconds = 3

[block_processor]
# first block of 2021 for Kusama is 6_015_486
# first block of 2021 for Polkadot is 2_700_565
start_block_number = 6_015_486

[validator_list_updater]
history_record_depth = 10
db_fetch_batch_size = 200

[dn]
# this many most recent records will always be kept in the database for reference
candidate_history_record_count = 5
data_endpoint = "https://nodes.web3.foundation/api/cohort/2-1/polkadot"
refresh_seconds = 300

[report]
max_era_index_range = 100
max_session_index_range = 100

[plotter]
tmp_dir_path = "/path/to/the/temporary/image/dir"
font_dir_path = "/path/to/the/fonts/dir"
font_sans_serif_family = "DejaVu Sans"

[telemetry]
# W3F       wss://telemetry-backend.w3f.community/feed
# Polkadot  wss://feed.telemetry.polkadot.io/feed
websocket_url = "wss://telemetry-backend.w3f.community/feed"

[notification_generator]
unclaimed_payout_check_delay_hours = 1

[notification_processor]
sleep_millis = 2000
email_from = "SubVT Notifications <mail@host.com>"
email_reply_to = "noreply@host.com"
email_account = "mail@host.com"
email_password = "password"
email_smtp_server_url = "mail.host.com"
email_smtp_server_tls_port = 587
apns_key_path = "/path/to/key_file.p8"
apns_key_id = "KEY_ID_12345"
apns_team_id = "APNS_TEAM_ID"
apns_topic = "APP_BUNDLE"
apns_is_production = false
fcm_api_key = "FCM_API_KEY"
# can be set with the SUBVT__NOTIFICATION_SENDER__KUSAMA_TELEGRAM_API_TOKEN
# environment variable
kusama_telegram_api_token = "kusama_telegram_api_token"
# can be set with the SUBVT__NOTIFICATION_SENDER__POLKADOT_TELEGRAM_API_TOKEN
# environment variable
polkadot_telegram_api_token = "polkadot_telegram_api_token"
# can be set with the SUBVT__NOTIFICATION_SENDER__TEMPLATE_DIR_PATH
# environment variable
template_dir_path = "/path/to/the/template/dir"

[telegram_bot]
api_token = "telegram_api_token"
# i64 array
admin_chat_ids = "1234,4563"
max_validators_per_chat = 25
# include the @
username = "@bot_username"

[referendum_updater]
refresh_seconds = 900

[metrics]
host = "127.0.0.1"
active_validator_list_server_port = 11003
app_service_port = 11013
block_processor_port = 11000
inactive_validator_list_server_port = 11004
network_status_server_port = 11006
network_status_updater_port = 11005
notification_generator_port = 11010
notification_processor_port = 11011
onekv_updater_port = 11007
report_service_port = 11009
telegram_bot_port = 11012
telemetry_processor_port = 11008
validator_details_server_port = 11002
validator_list_updater_port = 11001
referendum_updater_port = 11014
kline_updater_port = 11015
session_validator_performance_updater_port = 11016

[sub_id]
api_url = "https://sub.id/api/v1/"
nfts_path = "/nfts"

[app_service]
# max x users per IP per x minutes
user_registration_per_ip_limit_time_window_mins = 10
user_registration_per_ip_limit = 10

[kline_updater]
sleep_seconds = 3600
begin_year = 2022
begin_month = 1
begin_day = 1

[session_validator_performance_updater]
start_session_index = 5000
sleep_seconds = 60