version: "3.8"

services:
  subvt_kusama_block_processor:
    container_name: subvt_kusama_block_processor
    restart: unless-stopped
    image: "helikon/subvt-block-processor:${VERSION}"
    networks:
      - subvt_kusama
    environment:
      - SUBVT_ENV=${ENV}
      - SUBVT_NETWORK=kusama
      - SUBVT_CONFIG_DIR=/subvt/config
      # log level
      - SUBVT__LOG__SUBVT_LEVEL=${LOG_LEVEL}
      # metrics
      - SUBVT__METRICS__HOST=0.0.0.0
      # postgres
      - SUBVT__NETWORK_POSTGRES__HOST=subvt_kusama_postgres
      # rpc
      - SUBVT__SUBSTRATE__RPC_URL=${KUSAMA_RPC_URL}
      # start block
      - SUBVT__BLOCK_PROCESSOR__RELAY_START_BLOCK_NUMBER=${KUSAMA_BLOCK_PROCESSOR_RELAY_START_NUMBER}
      - SUBVT__BLOCK_PROCESSOR__ASSET_HUB_START_BLOCK_NUMBER=${KUSAMA_BLOCK_PROCESSOR_ASSET_HUB_START_NUMBER}
  subvt_kusama_validator_list_updater:
    container_name: subvt_kusama_validator_list_updater
    restart: unless-stopped
    image: "helikon/subvt-validator-list-updater:${VERSION}"
    depends_on:
      - subvt_kusama_block_processor
    networks:
      - subvt_kusama
    environment:
      - SUBVT_ENV=${ENV}
      - SUBVT_NETWORK=kusama
      - SUBVT_CONFIG_DIR=/subvt/config
      # log level
      - SUBVT__LOG__SUBVT_LEVEL=${LOG_LEVEL}
      # metrics
      - SUBVT__METRICS__HOST=0.0.0.0
      # redis
      - SUBVT__REDIS__URL=redis://subvt_kusama_redis:6379/
      # postgres
      - SUBVT__NETWORK_POSTGRES__HOST=subvt_kusama_postgres
      # rpc
      - SUBVT__SUBSTRATE__RPC_URL=${KUSAMA_RPC_URL}
      # history depth
      - SUBVT__VALIDATOR_LIST_UPDATER__HISTORY_RECORD_DEPTH=${KUSAMA_VALIDATOR_LIST_UPDATER_HISTORY_DEPTH}
      - SUBVT__VALIDATOR_LIST_UPDATER__DB_FETCH_BATCH_SIZE=${KUSAMA_VALIDATOR_LIST_UPDATER_DB_FETCH_BATCH_SIZE}
  subvt_kusama_active_validator_list_server:
    container_name: subvt_kusama_active_validator_list_server
    restart: unless-stopped
    image: "helikon/subvt-active-validator-list-server:${VERSION}"
    depends_on:
      - subvt_kusama_validator_list_updater
    networks:
      - subvt_kusama
    ports:
      - "${KUSAMA_ACTIVE_VALIDATOR_LIST_SERVER_PORT}:7889"
    environment:
      - SUBVT_ENV=${ENV}
      - SUBVT_NETWORK=kusama
      - SUBVT_CONFIG_DIR=/subvt/config
      # log level
      - SUBVT__LOG__SUBVT_LEVEL=${LOG_LEVEL}
      # metrics
      - SUBVT__METRICS__HOST=0.0.0.0
      # redis
      - SUBVT__REDIS__URL=redis://subvt_kusama_redis:6379/
  subvt_kusama_inactive_validator_list_server:
    container_name: subvt_kusama_inactive_validator_list_server
    restart: unless-stopped
    image: "helikon/subvt-inactive-validator-list-server:${VERSION}"
    depends_on:
      - subvt_kusama_validator_list_updater
    networks:
      - subvt_kusama
    ports:
      - "${KUSAMA_INACTIVE_VALIDATOR_LIST_SERVER_PORT}:7890"
    environment:
      - SUBVT_ENV=${ENV}
      - SUBVT_NETWORK=kusama
      - SUBVT_CONFIG_DIR=/subvt/config
      # log level
      - SUBVT__LOG__SUBVT_LEVEL=${LOG_LEVEL}
      # metrics
      - SUBVT__METRICS__HOST=0.0.0.0
      # redis
      - SUBVT__REDIS__URL=redis://subvt_kusama_redis:6379/
  subvt_kusama_validator_details_server:
    container_name: subvt_kusama_validator_details_server
    restart: unless-stopped
    image: "helikon/subvt-validator-details-server:${VERSION}"
    depends_on:
      - subvt_kusama_validator_list_updater
    networks:
      - subvt_kusama
    ports:
      - "${KUSAMA_VALIDATOR_DETAILS_SERVER_PORT}:7891"
    environment:
      - SUBVT_ENV=${ENV}
      - SUBVT_NETWORK=kusama
      - SUBVT_CONFIG_DIR=/subvt/config
      # log level
      - SUBVT__LOG__SUBVT_LEVEL=${LOG_LEVEL}
      # metrics
      - SUBVT__METRICS__HOST=0.0.0.0
      # redis
      - SUBVT__REDIS__URL=redis://subvt_kusama_redis:6379/
  subvt_kusama_network_status_updater:
    container_name: subvt_kusama_network_status_updater
    restart: unless-stopped
    image: "helikon/subvt-network-status-updater:${VERSION}"
    networks:
      - subvt_kusama
    environment:
      - SUBVT_ENV=${ENV}
      - SUBVT_NETWORK=kusama
      - SUBVT_CONFIG_DIR=/subvt/config
      # log level
      - SUBVT__LOG__SUBVT_LEVEL=${LOG_LEVEL}
      # metrics
      - SUBVT__METRICS__HOST=0.0.0.0
      # redis
      - SUBVT__REDIS__URL=redis://subvt_kusama_redis:6379/
      # rpc
      - SUBVT__SUBSTRATE__RPC_URL=${KUSAMA_RPC_URL}
  subvt_kusama_network_status_server:
    container_name: subvt_kusama_network_status_server
    restart: unless-stopped
    image: "helikon/subvt-network-status-server:${VERSION}"
    depends_on:
      - subvt_kusama_network_status_updater
    networks:
      - subvt_kusama
    ports:
      - "${KUSAMA_NETWORK_STATUS_SERVER_PORT}:7888"
    environment:
      - SUBVT_ENV=${ENV}
      - SUBVT_NETWORK=kusama
      - SUBVT_CONFIG_DIR=/subvt/config
      # log level
      - SUBVT__LOG__SUBVT_LEVEL=${LOG_LEVEL}
      # metrics
      - SUBVT__METRICS__HOST=0.0.0.0
      # redis
      - SUBVT__REDIS__URL=redis://subvt_kusama_redis:6379/
  subvt_kusama_onekv_updater:
    container_name: subvt_kusama_onekv_updater
    restart: unless-stopped
    image: "helikon/subvt-onekv-updater:${VERSION}"
    networks:
      - subvt_kusama
    environment:
      - SUBVT_ENV=${ENV}
      - SUBVT_NETWORK=kusama
      - SUBVT_CONFIG_DIR=/subvt/config
      # log level
      - SUBVT__LOG__SUBVT_LEVEL=${LOG_LEVEL}
      # metrics
      - SUBVT__METRICS__HOST=0.0.0.0
      # postgres
      - SUBVT__NETWORK_POSTGRES__HOST=subvt_kusama_postgres
  subvt_kusama_telemetry_processor:
    container_name: subvt_kusama_telemetry_processor
    restart: unless-stopped
    image: "helikon/subvt-telemetry-processor:${VERSION}"
    networks:
      - subvt_kusama
    environment:
      - SUBVT_ENV=${ENV}
      - SUBVT_NETWORK=kusama
      - SUBVT_CONFIG_DIR=/subvt/config
      # log level
      - SUBVT__LOG__SUBVT_LEVEL=${LOG_LEVEL}
      # metrics
      - SUBVT__METRICS__HOST=0.0.0.0
      # postgres
      - SUBVT__NETWORK_POSTGRES__HOST=subvt_kusama_postgres
  subvt_kusama_notification_generator:
    container_name: subvt_kusama_notification_generator
    restart: unless-stopped
    image: "helikon/subvt-notification-generator:${VERSION}"
    depends_on:
      - subvt_kusama_validator_list_updater
      - subvt_kusama_network_status_updater
    networks:
      - subvt_app
      - subvt_kusama
    environment:
      - SUBVT_ENV=${ENV}
      - SUBVT_NETWORK=kusama
      - SUBVT_CONFIG_DIR=/subvt/config
      # log level
      - SUBVT__LOG__SUBVT_LEVEL=${LOG_LEVEL}
      # metrics
      - SUBVT__METRICS__HOST=0.0.0.0
      # app postgres
      - SUBVT__APP_POSTGRES__HOST=subvt_app_postgres
      # network postgres
      - SUBVT__NETWORK_POSTGRES__HOST=subvt_kusama_postgres
      # redis
      - SUBVT__REDIS__URL=redis://subvt_kusama_redis:6379/
      # rpc
      - SUBVT__SUBSTRATE__RPC_URL=${KUSAMA_RPC_URL}
      # notification generator
      - SUBVT__NOTIFICATION_GENERATOR__UNCLAIMED_PAYOUT_CHECK_DELAY_HOURS=3
  subvt_kusama_report_service:
    container_name: subvt_kusama_report_service
    restart: unless-stopped
    image: "helikon/subvt-report-service:${VERSION}"
    networks:
      - subvt_kusama
    ports:
      - "${KUSAMA_REPORT_SERVICE_PORT}:7900"
    environment:
      - SUBVT_ENV=${ENV}
      - SUBVT_NETWORK=kusama
      - SUBVT_CONFIG_DIR=/subvt/config
      # log level
      - SUBVT__LOG__SUBVT_LEVEL=${LOG_LEVEL}
      # metrics
      - SUBVT__METRICS__HOST=0.0.0.0
      # postgres
      - SUBVT__NETWORK_POSTGRES__HOST=subvt_kusama_postgres
      # redis
      - SUBVT__REDIS__URL=redis://subvt_kusama_redis:6379/
  subvt_kusama_telegram_bot:
    container_name: subvt_kusama_telegram_bot
    restart: unless-stopped
    image: "helikon/subvt-telegram-bot:${VERSION}"
    networks:
      - subvt_app
      - subvt_kusama
    volumes:
      - ${TEMPLATE_DIR}:/subvt/template
      - ${TMP_DIR}:/subvt/tmp
      - ${FONT_DIR}:/subvt/font
    environment:
      - SUBVT_ENV=${ENV}
      - SUBVT_NETWORK=kusama
      - SUBVT_CONFIG_DIR=/subvt/config
      # log level
      - SUBVT__LOG__SUBVT_LEVEL=${LOG_LEVEL}
      # metrics
      - SUBVT__METRICS__HOST=0.0.0.0
      # app postgres
      - SUBVT__APP_POSTGRES__HOST=subvt_app_postgres
      # redis
      - SUBVT__REDIS__URL=redis://subvt_kusama_redis:6379/
      # network postgres
      - SUBVT__NETWORK_POSTGRES__HOST=subvt_kusama_postgres
      # template dir
      - SUBVT__NOTIFICATION_PROCESSOR__TEMPLATE_DIR_PATH=/subvt/template
      # telegram
      - SUBVT__TELEGRAM_BOT__API_TOKEN=${KUSAMA_TELEGRAM_API_TOKEN}
      - SUBVT__TELEGRAM_BOT__ADMIN_CHAT_IDS=${KUSAMA_TELEGRAM_ADMIN_CHAT_IDS}
      - SUBVT__TELEGRAM_BOT__USERNAME=${KUSAMA_TELEGRAM_BOT_USERNAME}
      # plotter
      - SUBVT__PLOTTER__TMP_DIR_PATH=/subvt/tmp
      - SUBVT__PLOTTER__FONT_DIR_PATH=/subvt/font
      # rpc
      - SUBVT__SUBSTRATE__RPC_URL=${KUSAMA_RPC_URL}
  subvt_kusama_referendum_updater:
    container_name: subvt_kusama_referendum_updater
    restart: unless-stopped
    image: "helikon/subvt-referendum-updater:${VERSION}"
    networks:
      - subvt_kusama
    environment:
      - SUBVT_ENV=${ENV}
      - SUBVT_NETWORK=kusama
      - SUBVT_CONFIG_DIR=/subvt/config
      # log level
      - SUBVT__LOG__SUBVT_LEVEL=${LOG_LEVEL}
      # metrics
      - SUBVT__METRICS__HOST=0.0.0.0
      # network postgres
      - SUBVT__NETWORK_POSTGRES__HOST=subvt_kusama_postgres
      # rpc
      - SUBVT__SUBSTRATE__RPC_URL=${KUSAMA_RPC_URL}
  subvt_kusama_kline_updater:
    container_name: subvt_kusama_kline_updater
    restart: unless-stopped
    image: "helikon/subvt-kline-updater:${VERSION}"
    networks:
      - subvt_kusama
    volumes:
      - ${TMP_DIR}:/subvt/tmp
    environment:
      - SUBVT_ENV=${ENV}
      - SUBVT_NETWORK=kusama
      - SUBVT_CONFIG_DIR=/subvt/config
      # log level
      - SUBVT__LOG__SUBVT_LEVEL=${LOG_LEVEL}
      # metrics
      - SUBVT__METRICS__HOST=0.0.0.0
      # network postgres
      - SUBVT__NETWORK_POSTGRES__HOST=subvt_kusama_postgres
      # kline updater
      - SUBVT__KLINE_UPDATER__TMP_DIR_PATH=/subvt/tmp
  subvt_kusama_session_validator_performance_updater:
    container_name: subvt_session_validator_performance_updater
    restart: unless-stopped
    image: "helikon/subvt-session-validator-performance-updater:${VERSION}"
    networks:
      - subvt_kusama
    volumes:
      - ${TMP_DIR}:/subvt/tmp
    environment:
      - SUBVT_ENV=${ENV}
      - SUBVT_NETWORK=kusama
      - SUBVT_CONFIG_DIR=/subvt/config
      # log level
      - SUBVT__LOG__SUBVT_LEVEL=${LOG_LEVEL}
      # metrics
      - SUBVT__METRICS__HOST=0.0.0.0
      # network postgres
      - SUBVT__NETWORK_POSTGRES__HOST=subvt_kusama_postgres
      # session validator performance updater
      - SUBVT__SESSION_VALIDATOR_PERFORMANCE_UPDATER__START_SESSION_INDEX=${KUSAMA_SESSION_VALIDATOR_PERFORMANCE_UPDATER_START_SESSION_INDEX}
networks:
  subvt_kusama:
    name: subvt_kusama
  subvt_app:
    name: subvt_app