{
 "title": "SubVT App",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "app_prometheus_data_source", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "App Service", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Connections",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "subvt_app_service::connection_count"
    }
   ]
  },
  {
   "title": "Requests",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "subvt_app_service::request_count"
    }
   ]
  },
  {
   "title": "Status Codes",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 6, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "subvt_app_service::response_status_code_count",
     "legendFormat": "{{status_code}}"
    }
   ]
  },
  {
   "title": "Response Time (ms)",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 10, "x": 14, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "subvt_app_service::response_time_ms_bucket",
     "legendFormat": "{{le}}"
    }
   ]
  },
  { "title": "Notification Processor", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Sent Notifications",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "subvt_notification_processor::sent_notification_count"
    }
   ]
  },
  {
   "title": "Kusama Era",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 4, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "subvt_notification_processor::era_index{network_name=\"kusama\"}"
    }
   ]
  },
  {
   "title": "Kusama Epoch",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 7, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "subvt_notification_processor::epoch_index{network_name=\"kusama\"}",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Polkadot Era",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 10, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "subvt_notification_processor::era_index{network_name=\"polkadot\"}"
    }
   ]
  },
  {
   "title": "Polkadot Epoch",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 13, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "subvt_notification_processor::epoch_index{network_name=\"polkadot\"}",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Notification Send Time (ms)",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "subvt_notification_processor::notification_send_time_ms_bucket",
     "legendFormat": "{{le}}"
    }
   ]
  }
 ]
}