{
 "title": "SubVT Network",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "prometheus_data_source", "query": "prometheus" },
   { "name": "subscan_json_api_data_source", "query": "marcusolsson-json-datasource" }
  ]
 },
 "panels": [
  { "title": "Subscan", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Subscan Best Block",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "cacheDurationSeconds": 5,
     "fields": [
      { "jsonPath": "$.data.blockNum", "type": "number" }
     ],
     "method": "GET",
     "urlPath": "/api/scan/metadata"
    }
   ]
  },
  {
   "title": "Subscan Finalized Block",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 5, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "cacheDurationSeconds": 5,
     "fields": [
      { "jsonPath": "$.data.finalized_blockNum", "type": "number" }
     ],
     "method": "GET",
     "urlPath": "/api/scan/metadata"
    }
   ]
  },
  { "title": "Telemetry Processor", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Best Block",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "subvt_telemetry_processor::best_block_number"
    }
   ]
  },
  {
   "title": "Finalized Block",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 5, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "subvt_telemetry_processor::finalized_block_number"
    }
   ]
  },
  {
   "title": "Nodes",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 10, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "subvt_telemetry_processor::node_count"
    }
   ]
  },
  { "title": "Block Processor", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Processed",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "subvt_block_processor::processed_finalized_block_number"
    }
   ]
  },
  {
   "title": "Target",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 5, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "subvt_block_processor::target_finalized_block_number"
    }
   ]
  },
  {
   "title": "Gap",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 10, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "subvt_block_processor::target_finalized_block_number - subvt_block_processor::processed_finalized_block_number"
    }
   ]
  },
  {
   "title": "Extrinsic Process Err.s",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "subvt_block_processor::extrinsic_process_error_count"
    }
   ]
  },
  {
   "title": "Event Process Err.s",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "subvt_block_processor::event_process_error_count"
    }
   ]
  },
  {
   "title": "Processing Time (ms)",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "subvt_block_processor::block_processing_time_ms_bucket",
     "legendFormat": "{{le}}"
    }
   ]
  },
  { "title": "Validator List Updater", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Processing Time (ms)",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "subvt_validator_list_updater::block_processing_time_ms_bucket",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Processed",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "subvt_validator_list_updater::processed_finalized_block_number"
    }
   ]
  },
  {
   "title": "Target",
   "type": "stat",
   "gridPos": { "h": 3, "w": 9, "x": 8, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "subvt_validator_list_updater::target_finalized_block_number"
    }
   ]
  },
  {
   "title": "Gap",
   "type": "stat",
   "gridPos": { "h": 3, "w": 7, "x": 17, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "subvt_validator_list_updater::target_finalized_block_number - subvt_validator_list_updater::processed_finalized_block_number"
    }
   ]
  },
  { "title": "Validator Details Server", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "Block",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "subvt_validator_details_server::current_finalized_block_number"
    }
   ]
  },
  {
   "title": "Subscription Count",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "subvt_validator_details_server::subscription_count"
    }
   ]
  },
  { "title": "Validator List Server", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "Active Subscriptions",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 28 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "subvt_active_validator_list_server::subscription_count"
    }
   ]
  },
  {
   "title": "Active Processed",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 28 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "subvt_active_validator_list_server::processed_finalized_block_number"
    }
   ]
  },
  {
   "title": "Active Target",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 28 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "subvt_active_validator_list_server::target_finalized_block_number"
    }
   ]
  },
  {
   "title": "Inactive Subscriptions",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 28 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "subvt_inactive_validator_list_server::subscription_count"
    }
   ]
  },
  {
   "title": "Inactive Processed",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 28 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "subvt_inactive_validator_list_server::processed_finalized_block_number"
    }
   ]
  },
  {
   "title": "Inactive Target",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 28 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "subvt_inactive_validator_list_server::target_finalized_block_number"
    }
   ]
  },
  { "title": "Network Status Updater", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "Processing Time (ms)",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "subvt_network_status_updater::block_processing_time_ms_bucket",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Processed Best",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "subvt_network_status_updater::processed_best_block_number"
    }
   ]
  },
  {
   "title": "Target Best",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "subvt_network_status_updater::target_best_block_number"
    }
   ]
  },
  {
   "title": "Gap",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "subvt_network_status_updater::target_best_block_number - subvt_network_status_updater::processed_best_block_number"
    }
   ]
  },
  { "title": "Network Status Server", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } },
  {
   "title": "Subscriptions",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 36 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "subvt_network_status_server::subscription_count"
    }
   ]
  },
  {
   "title": "Processed Best",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 5, "y": 36 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "subvt_network_status_server::processed_best_block_number"
    }
   ]
  },
  {
   "title": "Target Best",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 10, "y": 36 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "subvt_network_status_server::target_best_block_number"
    }
   ]
  },
  {
   "title": "Gap",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 15, "y": 36 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "subvt_network_status_server::target_best_block_number - subvt_network_status_server::processed_best_block_number"
    }
   ]
  },
  { "title": "1KV Updater", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 } },
  {
   "title": "Candidate List Fetch (ms)",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 40 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "subvt_onekv_updater::candidate_list_fetch_time_ms_bucket",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Nominators Fetch (ms)",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 40 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "subvt_onekv_updater::nominator_list_fetch_time_ms_bucket",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Last Run",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIsoNoDateIfToday" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "subvt_onekv_updater::last_run_timestamp_ms"
    }
   ]
  },
  {
   "title": "Total",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 3, "y": 43 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "subvt_onekv_updater::last_run_candidate_count"
    }
   ]
  },
  { "title": "Notification Generator", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 } },
  {
   "title": "Notifications",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 47 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(subvt_notification_generator::notification_count)"
    }
   ]
  },
  {
   "title": "Block",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 47 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "subvt_notification_generator::processed_block_number"
    }
   ]
  },
  {
   "title": "Block Errors",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 47 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "subvt_notification_generator::block_processor_error_count"
    }
   ]
  },
  {
   "title": "Val. List Block",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 47 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "subvt_notification_generator::processed_validator_list_block_number"
    }
   ]
  },
  {
   "title": "Val. List Errors",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 47 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "subvt_notification_generator::block_processor_error_count"
    }
   ]
  },
  { "title": "Telegram Bot", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 } },
  {
   "title": "Chats",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 51 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "subvt_telegram_bot::chat_count" }
   ]
  },
  {
   "title": "Validators",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 51 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "subvt_telegram_bot::validator_count"
    }
   ]
  },
  {
   "title": "Commands",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 51 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "subvt_telegram_bot::command_call_count",
     "legendFormat": "{{command}}"
    }
   ]
  },
  {
   "title": "Queries",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 51 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "subvt_telegram_bot::query_call_count",
     "legendFormat": "{{query}}"
    }
   ]
  },
  { "title": "Report Service", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 54 } },
  {
   "title": "Connections",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 55 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "subvt_report_service::connection_count"
    }
   ]
  },
  {
   "title": "Requests",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 55 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "subvt_report_service::request_count"
    }
   ]
  },
  {
   "title": "Status Codes",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 55 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "subvt_report_service::response_status_code_count",
     "legendFormat": "{{status_code}}"
    }
   ]
  },
  {
   "title": "Response Time (ms)",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "subvt_report_service::response_time_ms_bucket",
     "legendFormat": "{{le}}"
    }
   ]
  }
 ]
}