{
 "title": "SubVT",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "prometheus_data_source", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Block Processor", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Processing Time (ms)",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "subvt_block_processor::block_processing_time_ms_bucket",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Processed",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "subvt_block_processor::processed_finalized_block_number"
    }
   ]
  },
  {
   "title": "Target",
   "type": "stat",
   "gridPos": { "h": 3, "w": 9, "x": 8, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "subvt_block_processor::target_finalized_block_number"
    }
   ]
  },
  {
   "title": "Gap",
   "type": "stat",
   "gridPos": { "h": 3, "w": 7, "x": 17, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "subvt_block_processor::target_finalized_block_number - subvt_block_processor::processed_finalized_block_number"
    }
   ]
  },
  { "title": "Validator List Updater", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Processing Time (ms)",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "subvt_validator_list_updater::block_processing_time_ms_bucket",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Processed",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "subvt_validator_list_updater::processed_finalized_block_number"
    }
   ]
  },
  {
   "title": "Target",
   "type": "stat",
   "gridPos": { "h": 3, "w": 9, "x": 8, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "subvt_validator_list_updater::target_finalized_block_number"
    }
   ]
  },
  {
   "title": "Gap",
   "type": "stat",
   "gridPos": { "h": 3, "w": 7, "x": 17, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "subvt_validator_list_updater::target_finalized_block_number - subvt_validator_list_updater::processed_finalized_block_number"
    }
   ]
  },
  { "title": "Validator Details Server", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Block",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "subvt_validator_details_server::current_finalized_block_number"
    }
   ]
  },
  {
   "title": "Subscription Count",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "subvt_validator_details_server::subscription_count"
    }
   ]
  },
  { "title": "Network Status Updater", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "Processing Time (ms)",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "subvt_network_status_updater::block_processing_time_ms_bucket",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Processed",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "subvt_network_status_updater::processed_best_block_number"
    }
   ]
  },
  {
   "title": "Target",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "subvt_network_status_updater::target_best_block_number"
    }
   ]
  },
  {
   "title": "Gap",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "subvt_network_status_updater::target_best_block_number - subvt_network_status_updater::processed_best_block_number"
    }
   ]
  },
  { "title": "Network Status Server", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Processed",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "subvt_network_status_server::processed_best_block_number"
    }
   ]
  },
  {
   "title": "Target",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 5, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "subvt_network_status_server::target_best_block_number"
    }
   ]
  },
  {
   "title": "Gap",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 10, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "subvt_network_status_server::target_best_block_number - subvt_network_status_server::processed_best_block_number"
    }
   ]
  },
  {
   "title": "Subscriptions",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 15, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "subvt_network_status_server::subscription_count"
    }
   ]
  },
  { "title": "1KV Updater", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "Candidate Details Fetch (ms)",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 29 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "subvt_onekv_updater::candidate_details_fetch_time_ms_bucket",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Candidate List Fetch (ms)",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 29 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "subvt_onekv_updater::candidate_list_fetch_time_ms_bucket",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Nominators Fetch (ms)",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "subvt_onekv_updater::nominator_list_fetch_time_ms_bucket",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Last Run",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIsoNoDateIfToday" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "subvt_onekv_updater::last_run_timestamp_ms"
    }
   ]
  },
  {
   "title": "Total",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 15, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "subvt_onekv_updater::last_run_candidate_count"
    }
   ]
  },
  {
   "title": "Success",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 17, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "subvt_onekv_updater::last_run_candidate_details_fetch_success_count"
    }
   ]
  },
  {
   "title": "Error",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 19, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "subvt_onekv_updater::last_run_candidate_details_fetch_error_count"
    }
   ]
  }
 ]
}