ALTER TABLE sub_session_para_validator DROP COLUMN para_validator_index;
ALTER TABLE sub_session_para_validator DROP COLUMN para_validator_group_index;
ALTER TABLE sub_session_para_validator DROP COLUMN active_validator_index;
