-- Add up migration script here
ALTER TABLE sub_onekv_candidate DROP COLUMN IF EXISTS kusama_account_id;
ALTER TABLE sub_onekv_candidate DROP COLUMN IF EXISTS discovered_at;
ALTER TABLE sub_onekv_candidate DROP COLUMN IF EXISTS inclusion;
ALTER TABLE sub_onekv_candidate DROP COLUMN IF EXISTS commission;
ALTER TABLE sub_onekv_candidate DROP COLUMN IF EXISTS is_active;
ALTER TABLE sub_onekv_candidate DROP COLUMN IF EXISTS unclaimed_eras;
ALTER TABLE sub_onekv_candidate DROP COLUMN IF EXISTS nominated_at;
ALTER TABLE sub_onekv_candidate DROP COLUMN IF EXISTS offline_accumulated;
ALTER TABLE sub_onekv_candidate DROP COLUMN IF EXISTS offline_since;
ALTER TABLE sub_onekv_candidate DROP COLUMN IF EXISTS name;
ALTER TABLE sub_onekv_candidate DROP COLUMN IF EXISTS location;
ALTER TABLE sub_onekv_candidate DROP COLUMN IF EXISTS rank;
ALTER TABLE sub_onekv_candidate DROP COLUMN IF EXISTS version;
ALTER TABLE sub_onekv_candidate DROP COLUMN IF EXISTS is_valid;
ALTER TABLE sub_onekv_candidate DROP COLUMN IF EXISTS fault_count;
ALTER TABLE sub_onekv_candidate DROP COLUMN IF EXISTS score_updated_at;
ALTER TABLE sub_onekv_candidate DROP COLUMN IF EXISTS score_total;
ALTER TABLE sub_onekv_candidate DROP COLUMN IF EXISTS score_aggregate;
ALTER TABLE sub_onekv_candidate DROP COLUMN IF EXISTS score_inclusion;
ALTER TABLE sub_onekv_candidate DROP COLUMN IF EXISTS score_discovered;
ALTER TABLE sub_onekv_candidate DROP COLUMN IF EXISTS score_nominated;
ALTER TABLE sub_onekv_candidate DROP COLUMN IF EXISTS score_rank;
ALTER TABLE sub_onekv_candidate DROP COLUMN IF EXISTS score_unclaimed;
ALTER TABLE sub_onekv_candidate DROP COLUMN IF EXISTS score_bonded;
ALTER TABLE sub_onekv_candidate DROP COLUMN IF EXISTS score_faults;
ALTER TABLE sub_onekv_candidate DROP COLUMN IF EXISTS score_offline;
ALTER TABLE sub_onekv_candidate DROP COLUMN IF EXISTS score_randomness;
ALTER TABLE sub_onekv_candidate DROP COLUMN IF EXISTS score_span_inclusion;
ALTER TABLE sub_onekv_candidate DROP COLUMN IF EXISTS score_location;
ALTER TABLE sub_onekv_candidate DROP COLUMN IF EXISTS score_country;
ALTER TABLE sub_onekv_candidate DROP COLUMN IF EXISTS score_nominator_stake;
ALTER TABLE sub_onekv_candidate DROP COLUMN IF EXISTS score_provider;
ALTER TABLE sub_onekv_candidate DROP COLUMN IF EXISTS score_region;
ALTER TABLE sub_onekv_candidate DROP COLUMN IF EXISTS created_at;

ALTER TABLE sub_onekv_candidate ADD COLUMN IF NOT EXISTS identity text NOT NULL;
ALTER TABLE sub_onekv_candidate ADD COLUMN IF NOT EXISTS status VARCHAR(256) NOT NULL;
ALTER TABLE sub_onekv_candidate ADD COLUMN IF NOT EXISTS created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT now();

ALTER TABLE sub_onekv_nominator DROP COLUMN IF EXISTS onekv_id;
ALTER TABLE sub_onekv_nominator DROP COLUMN IF EXISTS stash_account_id;
ALTER TABLE sub_onekv_nominator DROP COLUMN IF EXISTS proxy_account_id;
ALTER TABLE sub_onekv_nominator DROP COLUMN IF EXISTS bonded_amount;
ALTER TABLE sub_onekv_nominator DROP COLUMN IF EXISTS proxy_delay;
ALTER TABLE sub_onekv_nominator DROP COLUMN IF EXISTS last_nomination_at;
ALTER TABLE sub_onekv_nominator DROP COLUMN IF EXISTS nominator_created_at;
ALTER TABLE sub_onekv_nominator DROP COLUMN IF EXISTS average_stake;
ALTER TABLE sub_onekv_nominator DROP COLUMN IF EXISTS reward_destination;
ALTER TABLE sub_onekv_nominator DROP COLUMN IF EXISTS created_at;
ALTER TABLE sub_onekv_nominator ADD COLUMN IF NOT EXISTS created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT now();

DROP TABLE IF EXISTS sub_onekv_candidate_validity;
DROP TABLE IF EXISTS sub_onekv_nominee;